### ISSUE TITLE
Improved support for debugging multiple processes in docker containers

### ISSUE THREAD

**Issue by yuatpocketgems** [microsoft/vscode-js-debug#861]
**Is your feature request related to a problem? Please describe.**
We have multiple interdependent micro services that are started using one single docker-compose file... separately.
```
# In docker-compose.yml
services:
  service:
    command: >
      bash -c "nodemon --inspect=0.0.0.0:1234 /${SERVICE_NAME}/src/server.js"
    ports:
      - 80 # Rest API
      - 1234 # debugger port for server
      - 5678 # debugger port for other programs (unittests)
    ...
```

We would start 1 service container with `docker-compose up`, and another service with a separate call to `docker-compose up` where `SERVICE_NAME` is different. To support running these containers at the same time, we had to resolve port conflicts.

We could have specified unique host ports for all services, but a) it would be high maintenance to keep the port number in docker-compose, launch config and `--inspect` in sync and b) with a few dozens of fixed ports, it's hard to guarantee all these ports are available on all dev machines.

As an alternative approach, I am able to make a reverse proxy for WebSocket protocol on port 1234 which is used by VSCode's JS debugger to connect to NodeJS's `--inspect` port. The proxy runs in a separate containers inside a custom network in docker shared by all containers. As part of starting a debug session, I would send a request to the proxy to update the "current debug target", so JS debugger's requests are forwarded to the right service container. But this would only work for debugging one single service, as there isn't enough information for me to tell which container a request to endpoint `/json` or `/json/list` is meant for.

I have looked at auto-attach, which doesn't seem to be working with node processes started within docker containers.
I have looked at VSCode's docker-compose related features, and they require too much configuring.

**Describe the feature you'd like**
Is it possible to expose the launch config's name as a header field in the `/json` and `/json/list` requests? It seems like changing https://github.com/microsoft/vscode-js-debug/blob/6daed2c5339f40c7b581a6d1cc3b62152dba1b3b/src/targets/node/nodeLauncher.ts#L149 so the config name is passed down and forward the config name under `x-jsdebug-config-name` in `getWSEndpoint` would suffice.

With this change, the launch and attach config need not to specify `port` or `attachSimplePort` any more, everything could go to port 9229 and be re-directed to containers appropriately.
